/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./resources/js/components/Base/Button/Button.vue')['default']
    CardStatisticsHorizontal: typeof import('./resources/js/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./resources/js/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./resources/js/@core/components/cards/CardStatisticsWithImages.vue')['default']
    Description: typeof import('./resources/js/components/Base/Headless/Dialog/Description.vue')['default']
    DevelopModule: typeof import('./resources/js/components/developModule/developModule.vue')['default']
    Dialog: typeof import('./resources/js/components/Base/Headless/Dialog/Dialog.vue')['default']
    Disclosure: typeof import('./resources/js/components/Base/Headless/Disclosure/Disclosure/Disclosure.vue')['default']
    Divider: typeof import('./resources/js/components/Base/Headless/Menu/Divider.vue')['default']
    ErrorHeader: typeof import('./resources/js/components/ErrorHeader.vue')['default']
    Footer: typeof import('./resources/js/components/Base/Headless/Dialog/Footer.vue')['default']
    FormCheck: typeof import('./resources/js/components/Base/Form/FormCheck/FormCheck.vue')['default']
    FormHelp: typeof import('./resources/js/components/Base/Form/FormHelp.vue')['default']
    FormInline: typeof import('./resources/js/components/Base/Form/FormInline.vue')['default']
    FormInput: typeof import('./resources/js/components/Base/Form/FormInput.vue')['default']
    FormLabel: typeof import('./resources/js/components/Base/Form/FormLabel.vue')['default']
    FormSelect: typeof import('./resources/js/components/Base/Form/FormSelect.vue')['default']
    FormSwitch: typeof import('./resources/js/components/Base/Form/FormSwitch/FormSwitch.vue')['default']
    FormTextarea: typeof import('./resources/js/components/Base/Form/FormTextarea.vue')['default']
    Group: typeof import('./resources/js/components/Base/Headless/Disclosure/Group.vue')['default']
    Header: typeof import('./resources/js/components/Base/Headless/Menu/Header.vue')['default']
    Input: typeof import('./resources/js/components/Base/Form/FormCheck/Input.vue')['default']
    InputGroup: typeof import('./resources/js/components/Base/Form/InputGroup/InputGroup.vue')['default']
    Item: typeof import('./resources/js/components/Base/Headless/Menu/Item.vue')['default']
    Items: typeof import('./resources/js/components/Base/Headless/Menu/Items.vue')['default']
    Label: typeof import('./resources/js/components/Base/Form/FormCheck/Label.vue')['default']
    List: typeof import('./resources/js/components/Base/Headless/Tab/List.vue')['default']
    LoadingIcon: typeof import('./resources/js/components/Base/LoadingIcon/LoadingIcon.vue')['default']
    Lucide: typeof import('./resources/js/components/Base/Lucide/Lucide.vue')['default']
    Menu: typeof import('./resources/js/components/Base/Headless/Menu/Menu.vue')['default']
    MoreBtn: typeof import('./resources/js/@core/components/MoreBtn.vue')['default']
    OdsCardList: typeof import('./resources/js/components/landingPage/OdsCardList.vue')['default']
    Ordertable: typeof import('./resources/js/components/orderTable/Ordertable.vue')['default']
    Panel: typeof import('./resources/js/components/Base/Headless/Dialog/Panel.vue')['default']
    Panels: typeof import('./resources/js/components/Base/Headless/Tab/Panels.vue')['default']
    Popover: typeof import('./resources/js/components/Base/Headless/Popover/Popover.vue')['default']
    Provider: typeof import('./resources/js/components/Base/Headless/Disclosure/Disclosure/Provider.vue')['default']
    ProviderLayer: typeof import('./resources/js/components/ProviderLayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slideover: typeof import('./resources/js/components/Base/Headless/Slideover/Slideover.vue')['default']
    Tab: typeof import('./resources/js/components/Base/Headless/Tab/Tab/Tab.vue')['default']
    Text: typeof import('./resources/js/components/Base/Form/InputGroup/Text.vue')['default']
    ThemeSwitcher: typeof import('./resources/js/@core/components/ThemeSwitcher.vue')['default']
    Title: typeof import('./resources/js/components/Base/Headless/Dialog/Title.vue')['default']
    ToastNotification: typeof import('./resources/js/components/Base/ToastNotification/ToastNotification.vue')['default']
  }
}
